name: riverpod_injected_workspace

environment:
  sdk: ^3.13.0

workspace:
  - packages/riverpod_injected
  - packages/riverpod_injected_generator

dev_dependencies:
  dart_pre_commit: ^6.1.4
  dart_test_tools: ^7.3.2
  riverpod_lint: ^3.1.9
